# Generated by Django 3.2 on 2021-06-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
