# Generated by Django 3.2 on 2021-06-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
